apiVersion: v1
kind: Service
metadata:
    name: hellokube-grpc
    labels:
        app: hellokube-grpc
spec:
    type: LoadBalancer
    selector:
        app: hellokube-grpc
    ports:
    - name: grpc
      port: 3030
      protocol: TCP
      targetPort: 3030
