// Code generated by protoc-gen-go. DO NOT EDIT.
// source: math.proto

/*
Package math_service is a generated protocol buffer package.

It is generated from these files:
	math.proto

It has these top-level messages:
	Operands
	Result
*/
package math_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A message with numeric operands for a math operation
type Operands struct {
	Dividend int32 `protobuf:"varint,1,opt,name=dividend" json:"dividend,omitempty"`
	Divisor  int32 `protobuf:"varint,2,opt,name=divisor" json:"divisor,omitempty"`
}

func (m *Operands) Reset()                    { *m = Operands{} }
func (m *Operands) String() string            { return proto.CompactTextString(m) }
func (*Operands) ProtoMessage()               {}
func (*Operands) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Operands) GetDividend() int32 {
	if m != nil {
		return m.Dividend
	}
	return 0
}

func (m *Operands) GetDivisor() int32 {
	if m != nil {
		return m.Divisor
	}
	return 0
}

// A message with numerical results from a math operation
type Result struct {
	Quotient float32 `protobuf:"fixed32,1,opt,name=quotient" json:"quotient,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Result) GetQuotient() float32 {
	if m != nil {
		return m.Quotient
	}
	return 0
}

func init() {
	proto.RegisterType((*Operands)(nil), "math_service.Operands")
	proto.RegisterType((*Result)(nil), "math_service.Result")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Math service

type MathClient interface {
	Divide(ctx context.Context, in *Operands, opts ...grpc.CallOption) (*Result, error)
}

type mathClient struct {
	cc *grpc.ClientConn
}

func NewMathClient(cc *grpc.ClientConn) MathClient {
	return &mathClient{cc}
}

func (c *mathClient) Divide(ctx context.Context, in *Operands, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/math_service.Math/Divide", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Math service

type MathServer interface {
	Divide(context.Context, *Operands) (*Result, error)
}

func RegisterMathServer(s *grpc.Server, srv MathServer) {
	s.RegisterService(&_Math_serviceDesc, srv)
}

func _Math_Divide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Operands)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServer).Divide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/math_service.Math/Divide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServer).Divide(ctx, req.(*Operands))
	}
	return interceptor(ctx, in, info, handler)
}

var _Math_serviceDesc = grpc.ServiceDesc{
	ServiceName: "math_service.Math",
	HandlerType: (*MathServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Divide",
			Handler:    _Math_Divide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "math.proto",
}

func init() { proto.RegisterFile("math.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0x2c, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0xb1, 0xe3, 0x8b, 0x53, 0x8b, 0xca, 0x32,
	0x93, 0x53, 0x95, 0x1c, 0xb8, 0x38, 0xfc, 0x0b, 0x52, 0x8b, 0x12, 0xf3, 0x52, 0x8a, 0x85, 0xa4,
	0xb8, 0x38, 0x52, 0x32, 0xcb, 0x32, 0x53, 0x52, 0xf3, 0x52, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58,
	0x83, 0xe0, 0x7c, 0x21, 0x09, 0x2e, 0x76, 0x10, 0xbb, 0x38, 0xbf, 0x48, 0x82, 0x09, 0x2c, 0x05,
	0xe3, 0x2a, 0xa9, 0x70, 0xb1, 0x05, 0xa5, 0x16, 0x97, 0xe6, 0x94, 0x80, 0xf4, 0x17, 0x96, 0xe6,
	0x97, 0x64, 0xa6, 0xe6, 0x95, 0x80, 0xf5, 0x33, 0x05, 0xc1, 0xf9, 0x46, 0x0e, 0x5c, 0x2c, 0xbe,
	0x89, 0x25, 0x19, 0x42, 0x16, 0x5c, 0x6c, 0x2e, 0x60, 0x33, 0x85, 0xc4, 0xf4, 0x90, 0x1d, 0xa2,
	0x07, 0x73, 0x85, 0x94, 0x08, 0xaa, 0x38, 0xc4, 0x6c, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xf3, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x35, 0xf2, 0xad, 0x9d, 0xcc, 0x00, 0x00, 0x00,
}
