apiVersion: v1
kind: Service
metadata:
    name: webserver
    labels:
        name: webserver
spec:
    ports:
        - name: http
          port: 80
    selector:
        name: webserver
    type: LoadBalancer
