apiVersion: v1
kind: ReplicationController
metadata:
    labels:
        name: webserver
    name: webserver-v1
spec:
    replicas: 1
    selector:
        name: webserver
        version: "1"
    template:
        metadata:
            labels:
                name: webserver
                version: "1"
        spec:
            containers:
            -   name: webserver
                image: gcr.io/ntrack-nonap/webserver
                ports:
                - containerPort: 3030
                imagePullPolicy: Always
