
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: say-deployment
spec:
    replicas: 3
    template:
        metadata:
            labels:
                app: say
        spec:
            containers:
            - name: say
              image: gcr.io/go-grpc/say
              ports:
              - containerPort: 8080
